### PR TITLE
fix: multiple GC runs

### LINKED ISSUE #74: Multiple GC runs for provider records
We share a datastore but every sybil will be running GC on the provider records in the store. So for 200 sybils we get 200 GC runs periodically that we could avoid 199 of.

If we could pass a garbage collector to the DHT or signal to the DHT to not GC somehow we could just do one sweep.

cc @daviddias @aschmahmann @willscott @Stebalien

### PR DESCRIPTION
**Pull request by alanshaw**
This adds a new flag and env var to allow provider record GC to be disabled: `-disable-prov-gc` / `HYDRA_DISABLE_PROV_GC`.

If GC is _enabled_ it automatically disables provider record GC for all Hydra heads other than the first.

It also renames the `Relay` option to `EnableRelay` to better communicate that it's a boolean flag.

Depends on:

* [x] https://github.com/libp2p/go-libp2p-kad-dht/pull/593
* [x] https://github.com/hnlq715/golang-lru/pull/6

fixes #74

### CODE REVIEW

File: head/head.go [hunk 1]
```diff
@@ -16,16 +17,22 @@ import (
...
-const highWater = 2000
-const gracePeriod = time.Minute
+const (
+	lowWater               = 1500
+	highWater              = 2000
+	gracePeriod            = time.Minute
+	provDisabledGCInterval = time.Hour * 24 * 365 * 100 // set really high to be "disabled"
+	provCacheSize          = 256
+	provCacheExpiry        = time.Hour
+)
```
Comment (daviddias) [inline head/head.go:35]: 👍🏽

File: head/head.go [hunk 2]
```diff
@@ -84,9 +91,7 @@ func NewHead(ctx context.Context, options ...opts.Option) (*Head, chan Bootstrap
 		return nil, nil, fmt.Errorf("failed to spawn libp2p node: %w", err)
 	}
 
-	dhtNode, err := dht.New(
-		ctx,
-		node,
+	o := []dht.Option{
```
Comment (daviddias) [inline head/head.go:94]: Developing the systems engineering traits of not using descriptive variable names, I see. Can I still bring you back? :)

Comment (alanshaw) [reply head/head.go:94]: Let me fix that...
